a = input ('digite algo:')
print('o tipo primitivo desse valor e', type(a))
print('so tem espaço?', a.isspace())
print('isso e um numero?',a.isnumeric())
print('isso e alfabetico ?',a.isalpha())
print ('esta em minuscula?',a.istitle())
